### ISSUE TITLE
ValueError: None is not a valid BillingPlan, what happened to my checkov install?  how to fix?

### ISSUE THREAD

**Issue by citrusoft** [bridgecrewio/checkov-vscode#118]
whatever workflow that you intended to steer customers towards bridgecrew is broken here...

Day 1: I follow these instructions https://www.checkov.io/1.Welcome/Quick%20Start.html
Day 2: I use the command-line to "level-up" my checkov
`
(.venv37) LTGO658175:tf TAHV$ checkov

       _               _              
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V / 
  \___|_| |_|\___|\___|_|\_\___/ \_/  
                                      
By bridgecrew.io | version: 2.2.180 

Would you like to “level up” your Checkov powers for free?  The upgrade includes: 

• Command line docker Image scanning
• Software Composition Analysis
• Centralized policy management
• Free bridgecrew.cloud account with API access
• Auto-fix remediation suggestions
• Enabling of VS Code Plugin
• Dashboard visualisation of Checkov scans
• Integration with GitHub for:
	◦ 	Automated Pull Request scanning
	◦ 	Auto remediation PR generation
• Integration with up to 100 cloud resources for:
	◦ 	Automated cloud resource checks
	◦ 	Resource drift detection

and much more...

It's easy and only takes 2 minutes. We can do it right now!

To Level-up, press 'y'... 

Level up? (y/n): y

Ok, let’s get you started on creating your free account! 

Enter your email address to begin:  // This will be used as your login at https://bridgecrew.cloud.

E-Mail: tahv@pge.com

Looks good!
Now choose an Organisation Name:  // This will enable collaboration with others who you can add to your team.

Organization name: PGE

Amazing!
We are now generating a personal API key to immediately enable some new features… 

Complete!

Saving API key to /Users/TAHV/.bridgecrew/credentials

Checkov will automatically check this location for a key.  If you forget it you’ll find it here
https://bridgecrew.cloud/integrations/api-token

Checkov Dashboard is configured, opening https://bridgecrew.cloud to explore your new powers.
FYI - check your inbox for login details! 

Congratulations! You’ve just super-sized your Checkov!  Why not test-drive image scanning now:

checkov --docker-image ubuntu --dockerfile-path /Users/bob/workspaces/bridgecrew/Dockerfile --repo-id bob/test --branch master

Or download our VS Code plugin:  https://github.com/bridgecrewio/checkov-vscode 

Interested in contributing to Checkov as an open source developer.  We thought you’d never ask.  Check us out at: 
https://github.com/bridgecrewio/checkov/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22 
`
Day 3: I try the same commands from the QuickStart and now it is broken with exceptions whose resolution is unknown to google search...
`
(.venv37) LTGO658175:tf TAHV$ checkov -d .
ValueError: None is not a valid BillingPlan

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/TAHV/.venv37/bin/checkov", line 9, in <module>
    sys.exit(run())
  File "/Users/TAHV/.venv37/lib/python3.7/site-packages/checkov/main.py", line 315, in run
    integration_feature_registry.run_pre_scan()
  File "/Users/TAHV/.venv37/lib/python3.7/site-packages/checkov/common/bridgecrew/integration_features/integration_feature_registry.py", line 26, in run_pre_scan
    integration.pre_scan()
  File "/Users/TAHV/.venv37/lib/python3.7/site-packages/checkov/common/bridgecrew/integration_features/features/licensing_integration.py", line 49, in pre_scan
    self.billing_plan = BillingPlan(license_details[BILLING_PLAN_KEY])
  File "/usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/enum.py", line 315, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/enum.py", line 569, in __new__
    raise exc
  File "/usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/enum.py", line 553, in __new__
    result = cls._missing_(value)
  File "/usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/enum.py", line 582, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: None is not a valid BillingPlan
`

I have  12 days left on my evaluation license.
I want quickly, simply to evaluate checkov for possible bridgecrew licensing, now its FUBAR.

How do I fix this ?

**Comment by SteveVaknin** [comment]
Hi @citrusoft 
I notified our billing development team to check, will keep you updated

**Comment by rotemavni** [comment]
Hello @citrusoft, 
The issue was fixed on checkov version `2.2.184`, please upgrade checkov to the latest version and you would not experience this issue any more.
