### ISSUE TITLE
Scan of terragoat files failing in Checkov

### ISSUE THREAD

**Issue by gbrandyb** [bridgecrewio/checkov-vscode#77]
having an issue with the vscode extension (Windows 10 Home, VSCode 1.61.2, Checkov ext 1.0.53) Trying to scan terragoat files and getting various errors in the log. For example, scanning s3.tf results in:[info]:
Running checkov:
[info]: c:\users\gordon\appdata\roaming\python\python38\Scripts\checkov -s --bc-api-key **** --repo-id gbrandyb/terragoat -f "c:\Users\Gordon\BridgeCrewTest\terragoat\terraform\aws\s3.tf" -o json
[debug]: Version command: c:\users\gordon\appdata\roaming\python\python38\Scripts\checkov -v
[debug]: Response from version command: 2.0.544
[warn]: Checkov stderr: Traceback (most recent call last):
  File "c:\Users\Gordon\AppData\Roaming\Python\Python38\Scripts\checkov.cmd", line 53, in <module>
[warn]: Checkov stderr:     run()
  File "C:\Users\Gordon\AppData\Roaming\Python\Python38\site-packages\checkov\main.py", line 202, in run
[warn]: Checkov stderr:      
[warn]: Checkov stderr: scan_reports = runner_registry.run(external_checks_dir=external_checks_dir, files=config.file,
  File "C:\Users\Gordon\AppData\Roaming\Python\Python38\site-packages\checkov\common\runners\runner_registry.py", line 63, in run
[warn]: Checkov stderr:     for scan_report in reports:
  File "C:\Users\Gordon\AppData\Local\Programs\Python\Python38\lib\concurrent\futures\_base.py", line 619, in result_iterator
[warn]: Checkov stderr:      
[warn]: Checkov stderr: yield fs.pop().result()
  File "C:\Users\Gordon\AppData\Local\Programs\Python\Python38\lib\concurrent\futures\_base.py", line 437, in result
[warn]: Checkov stderr:      
[warn]: Checkov stderr: return self.__get_result()
  File "C:\Users\Gordon\AppData\Local\Programs\Python\Python38\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
  File "C:\Users\Gordon\AppData\Local\Programs\Python\Python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Gordon\AppData\Roaming\Python\Python38\site-packages\checkov\common\runners\runner_registry.py", line 59, in <lambda>
    lambda runner: runner.run(root_folder, external_checks_dir=external_checks_dir, files=files,
  File "C:\Users\Gordon\AppData\Roaming\Python\Python38\site-packages\checkov\terraform\plan_runner.py", line 76, in run
[warn]: Checkov stderr:     graph_report = self.get_graph_checks_report(root_folder, runner_filter)
  File "C:\Users\Gordon\AppData\Roaming\Python\Python38\site-packages\checkov\terraform\runner.py", line 125, in get_graph_checks_report
[warn]: Checkov stderr:     entity_context, entity_evaluations = self.get_entity_context_and_evaluations(entity)
  File "C:\Users\Gordon\AppData\Roaming\Python\Python38\site-packages\checkov\terraform\plan_runner.py", line 82, in get_entity_context_and_evaluations
[warn]: Checkov stderr:     raw_context = self.get_entity_context(entity[CustomAttributes.BLOCK_NAME].split("."), entity[CustomAttributes.FILE_PATH])
  File "C:\Users\Gordon\AppData\Roaming\Python\Python38\site-packages\checkov\terraform\plan_runner.py", line 118, in get_entity_context
[warn]: Checkov stderr:     for resource in self.tf_definitions[full_file_path]['resource']:
KeyError: 'C:\\Users\\Gordon\\BridgeCrewTest\\terragoat\\terraform\\aws\\s3.tf'
[debug]: Checkov scan process exited with code 1
[debug]: Checkov task output: {"stdout":""}
[error]: Error occurred while running a checkov scan {"error":"Checkov exited with code 1"} (edited) 

Contact: gbrandyburg@paloaltonetworks.com (PANW pubsec SE)

**Comment by Rices** [comment]
Seconding this. My extension was working fine but started erroring out last week. I too run Windows 10 Home with VS Code.

Cloudformation seems to be working fine but Terraform seems to break. (Also a PANW SE)

**Comment by Rices** [comment]
@gbrandyb Incase you need a temporary fix. I was able to fix this up by installing docker for desktop on my Windows PC and then manualling pulling an older version of checkov and hardcoding that version into VS Code:

So after downloading Docker for Windows run:
docker pull bridgecrew/checkov:2.0.525

Then go to your settings in VS Code for Bridgecrew and hardcode the version to:
2.0.525

@Bridgecrew team, something in your later releases has broken Terraform scanning functionality.

**Comment by gbrandyb** [comment]
@Rices thanks I'll give that a shot.

@bridgecrewio team, just tested with vs extension 1.0.62 and checkov 2.0.560 and still seeing same error.
